---
# tasks file for fail2ban
- name: package
  package:
    name: '{{ fail2ban_packages }}'
    force_apt_get: yes
  tags:
    - fail2ban
    - package

- name: "{{ fail2ban_jail_local }}"
  template:
    src: 'jail.local.j2'
    dest: "{{ fail2ban_jail_local }}"
  notify:
    - fail2ban restart
  tags:
    - fail2ban
    - config
...
